name: C github action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make and run on ubuntu
        run: make hello && ./hello
  mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Make and run on macos
        run: make hello && ./hello
